function createfigure(Y1, Y2)
%CREATEFIGURE(Y1, Y2)
%  Y1:  vector of plot y data
%  Y2:  vector of stairs y data

%  Auto-generated by MATLAB on 07-May-2025 10:10:46

% Create figure
figure1 = figure('WindowState','maximized','Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(Y1,'DisplayName','Rewarding lever','MarkerSize',40,'Marker','.',...
    'LineStyle','none');

% Create stairs
stairs(Y2,'DisplayName','Reward probability','LineWidth',6,'LineStyle','-.',...
    'Color',[1 0 0]);

% Create ylabel
ylabel('Reward probability (%)');

% Create xlabel
xlabel('Trial');

% Create title
title('Task structure of TrainingTask','FontWeight','bold');

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[-10 190]); 
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[-0.1 1.1]);
box(axes1,'on');
hold(axes1,'off');

% Set the remaining axes properties for ABA_R 180 trials figure
% set(axes1,'ClippingStyle','rectangle','FontSize',24,'XTick',...
%     [0 20 40 60 80 100 120 140 160 180],'YTick',...
%     [0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1]);

% Set the remaining axes properties for TestTaskA 280 trials figure
set(axes1,'ClippingStyle','rectangle','FontSize',24,'XTick',...
    [0 40 80 120 160 200 240 280],'YTick',...
    [0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1]);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.741102428605989 0.755984536227424 0.123828127160668 0.0643898502024409]);

